# Generated by Django 3.1.3 on 2020-11-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, help_text='Meta description; 160 characters max.', max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated based on title. Full URL visible after saving...', max_length=300, unique=True)),
                ('social_media_image', models.ImageField(blank=True, upload_to='images/social/')),
                ('noindex_nofollow', models.BooleanField(default=False, help_text='Set the meta robots tag to noindex, nofollow')),
                ('publish_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='images/blogs/')),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('slug', 'publish_date')},
            },
        ),
    ]
