# Generated by Django 3.1.3 on 2020-11-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approved',
            field=models.BooleanField(default=False, help_text='Final approval. Must be checked for this page to be live.', verbose_name='Approved to Publish'),
        ),
        migrations.AddField(
            model_name='blog',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_approval_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_content_review_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_seo_review_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_visual_review_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='visual_review',
            field=models.BooleanField(default=False),
        ),
    ]
