# Generated by Django 3.1.3 on 2020-11-25 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, help_text='Meta description; 160 characters max.', max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated based on title. Full URL visible after saving...', max_length=300, unique=True)),
                ('social_media_image', models.ImageField(blank=True, upload_to='images/social/')),
                ('noindex_nofollow', models.BooleanField(default=False, help_text='Set the meta robots tag to noindex, nofollow')),
                ('content_review', models.BooleanField(default=False)),
                ('last_content_review_date', models.DateTimeField(auto_now=True)),
                ('visual_review', models.BooleanField(default=False)),
                ('last_visual_review_date', models.DateTimeField(auto_now=True)),
                ('seo_review', models.BooleanField(default=False)),
                ('last_seo_review_date', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False, help_text='Final approval. Must be checked for this page to be live.', verbose_name='Approved to Publish')),
                ('last_approval_date', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=300)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
